<?php
/**
 * ListsApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lettera
 *
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul>
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ListsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation frontpageGet
     *
     * Returns a list for a front page
     *
     * @param  int $start start (optional)
     * @param  int $limit limit (optional)
     * @param  string $category category (optional)
     * @param  string $paper paper (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ArticleStub[]
     */
    public function frontpageGet($start = null, $limit = null, $category = null, $paper = null)
    {
        list($response) = $this->frontpageGetWithHttpInfo($start, $limit, $category, $paper);
        return $response;
    }

    /**
     * Operation frontpageGetWithHttpInfo
     *
     * Returns a list for a front page
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ArticleStub[], HTTP status code, HTTP response headers (array of strings)
     */
    public function frontpageGetWithHttpInfo($start = null, $limit = null, $category = null, $paper = null)
    {
        $request = $this->frontpageGetRequest($start, $limit, $category, $paper);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ArticleStub[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ArticleStub[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ArticleStub[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation frontpageGetAsync
     *
     * Returns a list for a front page
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function frontpageGetAsync($start = null, $limit = null, $category = null, $paper = null)
    {
        return $this->frontpageGetAsyncWithHttpInfo($start, $limit, $category, $paper)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation frontpageGetAsyncWithHttpInfo
     *
     * Returns a list for a front page
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function frontpageGetAsyncWithHttpInfo($start = null, $limit = null, $category = null, $paper = null)
    {
        $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
        $request = $this->frontpageGetRequest($start, $limit, $category, $paper);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'frontpageGet'
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function frontpageGetRequest($start = null, $limit = null, $category = null, $paper = null)
    {
        if ($start !== null && $start > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.frontpageGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($start !== null && $start < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.frontpageGet, must be bigger than or equal to -9223372036854775808.');
        }

        if ($limit !== null && $limit > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.frontpageGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($limit !== null && $limit < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.frontpageGet, must be bigger than or equal to -9223372036854775808.');
        }


        $resourcePath = '/frontpage';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($category !== null) {
            $queryParams['category'] = ObjectSerializer::toQueryValue($category);
        }
        // query params
        if ($paper !== null) {
            $queryParams['paper'] = ObjectSerializer::toQueryValue($paper);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=utf-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=utf-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation latestGet
     *
     * Returns a list of latest articles
     *
     * @param  int $start start (optional)
     * @param  int $limit limit (optional)
     * @param  string $paper paper (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ArticleStub[]
     */
    public function latestGet($start = null, $limit = null, $paper = null)
    {
        list($response) = $this->latestGetWithHttpInfo($start, $limit, $paper);
        return $response;
    }

    /**
     * Operation latestGetWithHttpInfo
     *
     * Returns a list of latest articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ArticleStub[], HTTP status code, HTTP response headers (array of strings)
     */
    public function latestGetWithHttpInfo($start = null, $limit = null, $paper = null)
    {
        $request = $this->latestGetRequest($start, $limit, $paper);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ArticleStub[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ArticleStub[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ArticleStub[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation latestGetAsync
     *
     * Returns a list of latest articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function latestGetAsync($start = null, $limit = null, $paper = null)
    {
        return $this->latestGetAsyncWithHttpInfo($start, $limit, $paper)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation latestGetAsyncWithHttpInfo
     *
     * Returns a list of latest articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function latestGetAsyncWithHttpInfo($start = null, $limit = null, $paper = null)
    {
        $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
        $request = $this->latestGetRequest($start, $limit, $paper);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'latestGet'
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function latestGetRequest($start = null, $limit = null, $paper = null)
    {
        if ($start !== null && $start > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.latestGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($start !== null && $start < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.latestGet, must be bigger than or equal to -9223372036854775808.');
        }

        if ($limit !== null && $limit > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.latestGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($limit !== null && $limit < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.latestGet, must be bigger than or equal to -9223372036854775808.');
        }


        $resourcePath = '/latest';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($paper !== null) {
            $queryParams['paper'] = ObjectSerializer::toQueryValue($paper);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=utf-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=utf-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation mostreadGet
     *
     * Returns a list of most read articles
     *
     * @param  int $start start (optional)
     * @param  int $limit limit (optional)
     * @param  string $category category (optional)
     * @param  string $paper paper (optional)
     * @param  bool $only_subscribers only_subscribers (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ArticleStub[]
     */
    public function mostreadGet($start = null, $limit = null, $category = null, $paper = null, $only_subscribers = null)
    {
        list($response) = $this->mostreadGetWithHttpInfo($start, $limit, $category, $paper, $only_subscribers);
        return $response;
    }

    /**
     * Operation mostreadGetWithHttpInfo
     *
     * Returns a list of most read articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     * @param  bool $only_subscribers (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ArticleStub[], HTTP status code, HTTP response headers (array of strings)
     */
    public function mostreadGetWithHttpInfo($start = null, $limit = null, $category = null, $paper = null, $only_subscribers = null)
    {
        $request = $this->mostreadGetRequest($start, $limit, $category, $paper, $only_subscribers);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ArticleStub[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ArticleStub[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ArticleStub[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation mostreadGetAsync
     *
     * Returns a list of most read articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     * @param  bool $only_subscribers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mostreadGetAsync($start = null, $limit = null, $category = null, $paper = null, $only_subscribers = null)
    {
        return $this->mostreadGetAsyncWithHttpInfo($start, $limit, $category, $paper, $only_subscribers)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation mostreadGetAsyncWithHttpInfo
     *
     * Returns a list of most read articles
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     * @param  bool $only_subscribers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mostreadGetAsyncWithHttpInfo($start = null, $limit = null, $category = null, $paper = null, $only_subscribers = null)
    {
        $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
        $request = $this->mostreadGetRequest($start, $limit, $category, $paper, $only_subscribers);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'mostreadGet'
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $category (optional)
     * @param  string $paper (optional)
     * @param  bool $only_subscribers (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function mostreadGetRequest($start = null, $limit = null, $category = null, $paper = null, $only_subscribers = null)
    {
        if ($start !== null && $start > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.mostreadGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($start !== null && $start < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.mostreadGet, must be bigger than or equal to -9223372036854775808.');
        }

        if ($limit !== null && $limit > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.mostreadGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($limit !== null && $limit < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.mostreadGet, must be bigger than or equal to -9223372036854775808.');
        }


        $resourcePath = '/mostread';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($category !== null) {
            $queryParams['category'] = ObjectSerializer::toQueryValue($category);
        }
        // query params
        if ($paper !== null) {
            $queryParams['paper'] = ObjectSerializer::toQueryValue($paper);
        }
        // query params
        if ($only_subscribers !== null) {
            $queryParams['onlySubscribers'] = ObjectSerializer::toQueryValue($only_subscribers);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=utf-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=utf-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchGet
     *
     * Returns a list of search results
     *
     * @param  int $start start (optional)
     * @param  int $limit limit (optional)
     * @param  string $paper paper (optional)
     * @param  string $content_query content_query (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ArticleStub[]
     */
    public function searchGet($start = null, $limit = null, $paper = null, $content_query = null)
    {
        list($response) = $this->searchGetWithHttpInfo($start, $limit, $paper, $content_query);
        return $response;
    }

    /**
     * Operation searchGetWithHttpInfo
     *
     * Returns a list of search results
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     * @param  string $content_query (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ArticleStub[], HTTP status code, HTTP response headers (array of strings)
     */
    public function searchGetWithHttpInfo($start = null, $limit = null, $paper = null, $content_query = null)
    {
        $request = $this->searchGetRequest($start, $limit, $paper, $content_query);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ArticleStub[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ArticleStub[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ArticleStub[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchGetAsync
     *
     * Returns a list of search results
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     * @param  string $content_query (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchGetAsync($start = null, $limit = null, $paper = null, $content_query = null)
    {
        return $this->searchGetAsyncWithHttpInfo($start, $limit, $paper, $content_query)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchGetAsyncWithHttpInfo
     *
     * Returns a list of search results
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     * @param  string $content_query (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchGetAsyncWithHttpInfo($start = null, $limit = null, $paper = null, $content_query = null)
    {
        $returnType = '\OpenAPI\Client\Model\ArticleStub[]';
        $request = $this->searchGetRequest($start, $limit, $paper, $content_query);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchGet'
     *
     * @param  int $start (optional)
     * @param  int $limit (optional)
     * @param  string $paper (optional)
     * @param  string $content_query (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function searchGetRequest($start = null, $limit = null, $paper = null, $content_query = null)
    {
        if ($start !== null && $start > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.searchGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($start !== null && $start < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$start" when calling ListsApi.searchGet, must be bigger than or equal to -9223372036854775808.');
        }

        if ($limit !== null && $limit > 9223372036854775807) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.searchGet, must be smaller than or equal to 9223372036854775807.');
        }
        if ($limit !== null && $limit < -9223372036854775808) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ListsApi.searchGet, must be bigger than or equal to -9223372036854775808.');
        }


        $resourcePath = '/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($start !== null) {
            $queryParams['start'] = ObjectSerializer::toQueryValue($start);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($paper !== null) {
            $queryParams['paper'] = ObjectSerializer::toQueryValue($paper);
        }
        // query params
        if ($content_query !== null) {
            $queryParams['contentQuery'] = ObjectSerializer::toQueryValue($content_query);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=utf-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=utf-8'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
