<?php
/**
 * ArticleType
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lettera
 *
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ArticleType Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ArticleType
{
    /**
     * Possible values of this enum
     */
    const NYHET_STOR = 'NyhetStor';
    const NYHET_LITEN = 'NyhetLiten';
    const NYHET_RELATERADE = 'NyhetRelaterade';
    const OPINION = 'Opinion';
    const KATASTROF_STOR = 'KatastrofStor';
    const KATASTROF_LITEN = 'KatastrofLiten';
    const ADVERTORIAL = 'Advertorial';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NYHET_STOR,
            self::NYHET_LITEN,
            self::NYHET_RELATERADE,
            self::OPINION,
            self::KATASTROF_STOR,
            self::KATASTROF_LITEN,
            self::ADVERTORIAL,
        ];
    }
}


