<?php
/**
 * ArticleStubTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lettera
 *
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul>
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ArticleStubTest Class Doc Comment
 *
 * @category    Class
 * @description ArticleStub
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ArticleStubTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArticleStub"
     */
    public function testArticleStub()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "article_title"
     */
    public function testPropertyArticleTitle()
    {
    }

    /**
     * Test attribute "authors"
     */
    public function testPropertyAuthors()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "preamble"
     */
    public function testPropertyPreamble()
    {
    }

    /**
     * Test attribute "list_image"
     */
    public function testPropertyListImage()
    {
    }

    /**
     * Test attribute "premium"
     */
    public function testPropertyPremium()
    {
    }

    /**
     * Test attribute "publishing_time"
     */
    public function testPropertyPublishingTime()
    {
    }

    /**
     * Test attribute "update_time"
     */
    public function testPropertyUpdateTime()
    {
    }

    /**
     * Test attribute "related_articles"
     */
    public function testPropertyRelatedArticles()
    {
    }

    /**
     * Test attribute "article_type"
     */
    public function testPropertyArticleType()
    {
    }

    /**
     * Test attribute "article_type_details"
     */
    public function testPropertyArticleTypeDetails()
    {
    }

    /**
     * Test attribute "paper"
     */
    public function testPropertyPaper()
    {
    }

    /**
     * Test attribute "share_url"
     */
    public function testPropertyShareUrl()
    {
    }

    /**
     * Test attribute "live_reporting"
     */
    public function testPropertyLiveReporting()
    {
    }

    /**
     * Test attribute "article_priority"
     */
    public function testPropertyArticlePriority()
    {
    }
}
