<?php
/**
 * BlockTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lettera
 *
 * KSF Media's articles service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * BlockTest Class Doc Comment
 *
 * @category    Class
 * @description Block
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BlockTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Block"
     */
    public function testBlock()
    {
    }

    /**
     * Test attribute "paragraph"
     */
    public function testPropertyParagraph()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "box"
     */
    public function testPropertyBox()
    {
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
    }

    /**
     * Test attribute "footnote"
     */
    public function testPropertyFootnote()
    {
    }

    /**
     * Test attribute "question"
     */
    public function testPropertyQuestion()
    {
    }

    /**
     * Test attribute "quote"
     */
    public function testPropertyQuote()
    {
    }
}
