<?php
/**
 * ListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lettera
 *
 * <h2>KSF Media's articles service</h2> Changelog for V3: <ul><li>Unified <code>ListArticle</code> and <code>RelatedArticle</code> into a single type <code>ArticleStub</code>. NOTE: In contrast to the old types, <code>ArticleStub.relatedArticles</code> is now an optional value.</li> <li>Added endpoint <code>/article/{uuid}/stub</code></li> <li>Removed deprecated endpoint <code>/article/search</code></li> </ul>
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for frontpageGet
     *
     * Returns a list for a front page.
     *
     */
    public function testFrontpageGet()
    {
    }

    /**
     * Test case for latestGet
     *
     * Returns a list of latest articles.
     *
     */
    public function testLatestGet()
    {
    }

    /**
     * Test case for mostreadGet
     *
     * Returns a list of most read articles.
     *
     */
    public function testMostreadGet()
    {
    }

    /**
     * Test case for presetPresetCategoryGet
     *
     * Load a preset model.
     *
     */
    public function testPresetPresetCategoryGet()
    {
    }

    /**
     * Test case for presetPresetCategoryPost
     *
     * Update a preset model.
     *
     */
    public function testPresetPresetCategoryPost()
    {
    }

    /**
     * Test case for scoredPost
     *
     * List recent articles sorted by given scoring weights.
     *
     */
    public function testScoredPost()
    {
    }

    /**
     * Test case for scoredPresetGet
     *
     * List recent articles sorted by preset scoring.
     *
     */
    public function testScoredPresetGet()
    {
    }

    /**
     * Test case for searchGet
     *
     * Returns a list of search results.
     *
     */
    public function testSearchGet()
    {
    }

    /**
     * Test case for tagTagGet
     *
     * Returns a list of latest articles by tag.
     *
     */
    public function testTagTagGet()
    {
    }
}
